/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    36KNews: typeof import('./src/components/news/36KNews.vue')['default']
    BingPic: typeof import('./src/components/bing-pic/BingPic.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    NavigateList: typeof import('./src/components/navigates/NavigateList.vue')['default']
    NewsList: typeof import('./src/components/news/NewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search/SearchInput.vue')['default']
    ZhiHuHots: typeof import('./src/components/news/ZhiHuHots.vue')['default']
  }
}
